name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: "contains(github.event.head_commit.message, 'release')"

    timeout-minutes: 10
    runs-on: ubuntu-latest

    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Run Test
        run: pnpm test
